services:
  api: 
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=12a26e3b2ffa1fdd14304ced9e550a2977167f72b165624b99ebd67d37bc4cb2
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  postgres:
    image: postgres:17.5
    environment: 
      - POSTGRES_PASSWORD=password123
      - POSTGES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
