name: Build and deploy code

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  job_named_bob:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: testetsetststst
        run: echo "your lighsaber will make a fine addition to my collection"